version: '3'

services:
  app:
    build: ./
    tty: true
    volumes:
      - ./nextjs-with-typescript:/usr/app
      - ./home/:${HOME}
    command: sh -c "yarn dev"
    ports:
      - "3000:3000"
    user: node
